Public NameVendor As String 'Производитель
Public FileName  As String 'ИмяФайлаБазы
Public NameListExcel As String 'ИмяЛиста
Public FirstRow As Long 'Строка начало
Public LastRow As Long 'СтрокаКонец
Public Artikul As Long 'СтолбецАртикул
Public Nazvanie As Long 'СтолбецНазвание
Public Cena As Long 'СтолбецЦена
Public Ed As Long 'СтолбецЕдиницы
Public Kategoriya As Long 'СтолбецКатегория
Public Gruppa As Long 'СтолбецГруппа
Public Podgruppa As Long 'СтолбецПодгруппа

