Public Proizvoditel As String 'Производитель
Public FileName  As String 'ИмяФайлаБазы
Public NameListExcel As String 'ИмяЛиста
Public StolbArtikul As Long 'СтолбецАртикул
Public StolbNazvanie As Long 'СтолбецНазвание
Public StolbCena As Long 'СтолбецЦена
Public StolbEd As Long 'СтолбецЕдиницы
Public StolbKategoriya As Long 'СтолбецКатегория
Public StolbGruppa As Long 'СтолбецГруппа
Public StolbPodgruppa As Long 'СтолбецПодгруппа

