Public NameVendor As String 'Производитель
Public FileName  As String 'ИмяФайлаБазы
Public NameListExcel As String 'ИмяЛиста
Public FirstRow As String 'Строка начало
Public LastRow As String 'СтрокаКонец
Public Artikul As String 'СтолбецАртикул
Public Nazvanie As String 'СтолбецНазвание
Public Cena As String 'СтолбецЦена
Public Ed As String 'СтолбецЕдиницы
Public Kategoriya As String 'СтолбецКатегория
Public Gruppa As String 'СтолбецГруппа
Public Podgruppa As String 'СтолбецПодгруппа

